### ISSUE TITLE
vgm error,  plays on vgm website without issues

### ISSUE THREAD

**Issue by arrowgent** [ValleyBell/libvgm#96]
https://vgmrips.net/packs/pack/lagrange-point-family-computer

./player Lagrange\ Point_X_error_\[FDS\]\ 06\ Satellite\ Base.vgz 
```
Opening Audio Device ...
Using driver PulseAudio.
Opening Device 0 ...
Loading Lagrange Point_X_error_[FDS] 06 Satellite Base.vgz ...  VGM v170, Total Length: 60.03 s, Loop Length: 59.54 s
Song Title: Satellite Base
[Warn ] VGM: Unknown VGM command 00 found! (filePos 0x000122)
[Warn ] VGM: Unknown VGM command 00 found! (filePos 0x000123)
[Warn ] VGM: Unknown VGM command 00 found! (filePos 0x000124)
[Warn ] VGM: Unknown VGM command 00 found! (filePos 0x000125)
[Warn ] VGM: Unknown VGM command 00 found! (filePos 0x000126)
[Warn ] VGM: Unknown VGM command 00 found! (filePos 0x000127)
[Error] VGM: Invalid VGM command 04 found! (filePos 0x000128)
Song End..47 / 119.57 ...   
Done.
```

./vgmplay Lagrange\ Point_X_error_\[FDS\]\ 06\ Satellite\ Base.vgz 
```

VGM Player
----------

File Name:      Lagrange Point_X_error_[FDS] 06 Satellite Base.vgz

VGM Warn: Unknown VGM command 00 found! (filePos 0x000122)
VGM Warn: Unknown VGM command 00 found! (filePos 0x000123)
VGM Warn: Unknown VGM command 00 found! (filePos 0x000124)
VGM Warn: Unknown VGM command 00 found! (filePos 0x000125)
VGM Warn: Unknown VGM command 00 found! (filePos 0x000126)
VGM Warn: Unknown VGM command 00 found! (filePos 0x000127)
VGM Error: Invalid VGM command 04 found! (filePos 0x000128)
Track Title:    Satellite Base
Game Name:      Lagrange Point
System:         Family Computer
Composer:       Konami Kukeiha Club
Release:        1991-04-26
Format:         VGM 1.70    Gain: 2.48    Loop: Yes (00:59.54)
VGM by:         Gnome
Notes:          

Used chips:     VRC7, NES APU  

Finish   0.00%  00:00.97 / 01:00.03 seconds  
```

./vgm2wav Lagrange\ Point_X_error_\[FDS\]\ 06\ Satellite\ Base.vgz 6.wav
```
TITLE: Satellite Base
TITLE-JPN: サテライトベース (サテライトベース、ヴェスタ町)
GAME: Lagrange Point
GAME-JPN: ラグランジュポイント
SYSTEM: Family Computer
SYSTEM-JPN: ファミリーコンピュータ
ARTIST: Konami Kukeiha Club
ARTIST-JPN: コナミ矩形波倶楽部
DATE: 1991-04-26
ENCODED_BY: Gnome
COMMENT: 
PlayerName: VGM
SongInfo: VGM v1.70, Rate 1/44100, Len 2647111, Loop at 2625802, devices: 2
  Dev 0: Type 0x01 #0, Core EMU, Clock 3579545, Rate 49715, Volume 0x200
    Cores: EMU MAME NUKE
  Dev 1: Type 0x14 #0, Core NSFP, Clock 1789773, Rate 447443, Volume 0x80
    Cores: NSFP MAME

Rendering Lagrange Point_X_error_[FDS] 06 Satellite Base.vgz to 6.wav
Samplerate: 44100
BPS: 16
Channels: 2
Length: 02:07.567
[----------]
```
no audio in the wav file

also extracted the VGM from the gzip file
vgz = vgm.gz
same error

i dont know if this is a libvgm issue?
the vgz file is damaged?
**oh i see, the website plays MP3.**  

i guess this would need to be fixed in the vgm file and reported at vgmrip
